[DEFAULT]
#used by JS
ServerHostname = 192.168.176.30
NumberOfFiles = 3
EncryptionKey = exampleKey
UploadDirectory= uploads

[SERVER]
Port = 80
DebugMode = Off

[ENCRYPTION]
SaltSize = 16
IVSize = 16
KeyIterations = 100000
