[DEFAULT]
#used by JS
ServerHostname = localhost
NumberOfFiles = 3
EncryptionKey = exampleKey
UploadDirectory= uploads
ApiToken = change-me

[SERVER]
Port = 80
DebugMode = Off

[ENCRYPTION]
SaltSize = 16
IVSize = 16
KeyIterations = 100000
